spring:
  application:
    name: developer

eureka:
  client:
    initial-instance-info-replication-interval-seconds: 2
    instance-info-replication-interval-seconds: 1
    registry-fetch-interval-seconds: 1